{-# LANGUAGE MultiParamTypeClasses #-}
{-# LANGUAGE TemplateHaskell       #-}
module SpirV.OpCode where

import           Language.Haskell.TH
import           Control.Monad

class OpCodeClass op repr where
  unliftRepr :: op repr -> repr
  liftRepr :: repr -> op repr

declareOp :: Name -> Q Dec
-- data $name a = $name a
declareOp name = return $ DataD [] name [PlainTV a] [NormalC name [(NotStrict, VarT a)]] []
  where a = mkName "a"

genOpInstance :: Name -> Q [Dec]
genOpInstance name =
  [d|instance OpCodeClass $(conT name) repr where
        unliftRepr $(conP name [varP r]) = $(varE r)
        liftRepr = $(conE name)
  |]
  where r = mkName "r"

ops :: [Name]
ops = fmap mkName
  [ "OpAccessChain"
  , "OpAll"
  , "OpAny"
  , "OpArrayLength"
  , "OpAsyncGroupCopy"
  , "OpAtomicAnd"
  , "OpAtomicCompareExchange"
  , "OpAtomicCompareExchangeWeak"
  , "OpAtomicExchange"
  , "OpAtomicIAdd"
  , "OpAtomicIDecrement"
  , "OpAtomicIIncrement"
  , "OpAtomicInit"
  , "OpAtomicISub"
  , "OpAtomicLoad"
  , "OpAtomicOr"
  , "OpAtomicStore"
  , "OpAtomicUMax"
  , "OpAtomicUMin"
  , "OpAtomicXor"
  , "OpBitcast"
  , "OpBitwiseAnd"
  , "OpBitwiseOr"
  , "OpBitwiseXor"
  , "OpBranch"
  , "OpBranchConditional"
  , "OpBuildNDRange"
  , "OpCaptureEventProfilingInfo"
  , "OpCommitReadPipe"
  , "OpCommitWritePipe"
  , "OpCompileFlag"
  , "OpCompositeConstruct"
  , "OpCompositeExtract"
  , "OpCompositeInsert"
  , "OpConstant"
  , "OpConstantComposite"
  , "OpConstantFalse"
  , "OpConstantNullObject"
  , "OpConstantNullPointer"
  , "OpConstantSampler"
  , "OpConstantTrue"
  , "OpControlBarrier"
  , "OpConvertFToS"
  , "OpConvertFToU"
  , "OpConvertPtrToU"
  , "OpConvertSToF"
  , "OpConvertUToF"
  , "OpConvertUToPtr"
  , "OpCopyMemory"
  , "OpCopyMemorySized"
  , "OpCopyObject"
  , "OpCreateUserEvent"
  , "OpDecorate"
  , "OpDecorationGroup"
  , "OpDot"
  , "OpDPdx"
  , "OpDPdxCoarse"
  , "OpDPdxFine"
  , "OpDPdy"
  , "OpDPdyCoarse"
  , "OpDPdyFine"
  , "OpEmitStreamVertex"
  , "OpEmitVertex"
  , "OpEndPrimitive"
  , "OpEndStreamPrimitive"
  , "OpEnqueueKernel"
  , "OpEnqueueMarker"
  , "OpEntryPoint"
  , "OpExecutionMode"
  , "OpExtension"
  , "OpExtInst"
  , "OpExtInstImport"
  , "OpFAdd"
  , "OpFConvert"
  , "OpFDiv"
  , "OpFMod"
  , "OpFMul"
  , "OpFNegate"
  , "OpFOrdEqual"
  , "OpFOrdGreaterThan"
  , "OpFOrdGreaterThanEqual"
  , "OpFOrdLessThan"
  , "OpFOrdLessThanEqual"
  , "OpFOrdNotEqual"
  , "OpFRem"
  , "OpFSub"
  , "OpFunction"
  , "OpFunctionCall"
  , "OpFunctionEnd"
  , "OpFunctionParameter"
  , "OpFUnordEqual"
  , "OpFUnordGreaterThan"
  , "OpFUnordGreaterThanEqual"
  , "OpFUnordLessThan"
  , "OpFUnordLessThanEqual"
  , "OpFUnordNotEqual"
  , "OpFwidth"
  , "OpFwidthCoarse"
  , "OpFwidthFine"
  , "OpGenericCastToPtr"
  , "OpGenericCastToPtrExplicit"
  , "OpGenericPtrMemSemantics"
  , "OpGetDefaultQueue"
  , "OpGetKernelNDrangeMaxSubGroupSize"
  , "OpGetKernelNDrangeSubGroupCount"
  , "OpGetKernelPreferredWorkGroupSizeMultiple"
  , "OpGetKernelWorkGroupSize"
  , "OpGetMaxPipePackets"
  , "OpGetNumPipePackets"
  , "OpGroupAll"
  , "OpGroupAny"
  , "OpGroupBroadcast"
  , "OpGroupCommitReadPipe"
  , "OpGroupCommitWritePipe"
  , "OpGroupDecorate"
  , "OpGroupFAdd"
  , "OpGroupFMax"
  , "OpGroupFMin"
  , "OpGroupIAdd"
  , "OpGroupMemberDecorate"
  , "OpGroupReserveReadPipePackets"
  , "OpGroupReserveWritePipePackets"
  , "OpGroupSMax"
  , "OpGroupSMin"
  , "OpGroupUMax"
  , "OpGroupUMin"
  , "OpIAdd"
  , "OpIEqual"
  , "OpImagePointer"
  , "OpIMul"
  , "OpInBoundsAccessChain"
  , "OpINotEqual"
  , "OpIsFinite"
  , "OpIsInf"
  , "OpIsNan"
  , "OpIsNormal"
  , "OpISub"
  , "OpIsValidEvent"
  , "OpIsValidReserveId"
  , "OpKill"
  , "OpLabel"
  , "OpLessOrGreater"
  , "OpLifetimeStart"
  , "OpLifetimeStop"
  , "OpLine"
  , "OpLoad"
  , "OpLogicalAnd"
  , "OpLogicalOr"
  , "OpLogicalXor"
  , "OpLoopMerge"
  , "OpMatrixTimesMatrix"
  , "OpMatrixTimesScalar"
  , "OpMatrixTimesVector"
  , "OpMemberDecorate"
  , "OpMemberName"
  , "OpMemoryBarrier"
  , "OpMemoryModel"
  , "OpName"
  , "OpNop"
  , "OpNot"
  , "OpOrdered"
  , "OpOuterProduct"
  , "OpPhi"
  , "OpPtrCastToGeneric"
  , "OpReadPipe"
  , "OpReleaseEvent"
  , "OpReservedReadPipe"
  , "OpReservedWritePipe"
  , "OpReserveReadPipePackets"
  , "OpReserveWritePipePackets"
  , "OpRetainEvent"
  , "OpReturn"
  , "OpReturnValue"
  , "OpSampler"
  , "OpSConvert"
  , "OpSDiv"
  , "OpSelect"
  , "OpSelectionMerge"
  , "OpSetUserEventStatus"
  , "OpSGreaterThan"
  , "OpSGreaterThanEqual"
  , "OpShiftLeftLogical"
  , "OpShiftRightArithmetic"
  , "OpShiftRightLogical"
  , "OpSignBitSet"
  , "OpSLessThan"
  , "OpSLessThanEqual"
  , "OpSMod"
  , "OpSNegate"
  , "OpSource"
  , "OpSourceExtension"
  , "OpSpecConstant"
  , "OpSpecConstantComposite"
  , "OpSpecConstantFalse"
  , "OpSpecConstantTrue"
  , "OpSRem"
  , "OpStore"
  , "OpString"
  , "OpSwitch"
  , "OpTextureFetchBuffer"
  , "OpTextureFetchSample"
  , "OpTextureFetchTexel"
  , "OpTextureFetchTexelOffset"
  , "OpTextureGather"
  , "OpTextureGatherOffset"
  , "OpTextureGatherOffsets"
  , "OpTextureQueryLevels"
  , "OpTextureQueryLod"
  , "OpTextureQuerySamples"
  , "OpTextureQuerySize"
  , "OpTextureQuerySizeLod"
  , "OpTextureSample"
  , "OpTextureSampleDref"
  , "OpTextureSampleGrad"
  , "OpTextureSampleGradOffset"
  , "OpTextureSampleLod"
  , "OpTextureSampleLodOffset"
  , "OpTextureSampleOffset"
  , "OpTextureSampleProj"
  , "OpTextureSampleProjGrad"
  , "OpTextureSampleProjGradOffset"
  , "OpTextureSampleProjLod"
  , "OpTextureSampleProjLodOffset"
  , "OpTextureSampleProjOffset"
  , "OpTranspose"
  , "OpTypeArray"
  , "OpTypeBool"
  , "OpTypeDeviceEvent"
  , "OpTypeEvent"
  , "OpTypeFilter"
  , "OpTypeFloat"
  , "OpTypeFunction"
  , "OpTypeInt"
  , "OpTypeMatrix"
  , "OpTypeOpaque"
  , "OpTypePipe"
  , "OpTypePointer"
  , "OpTypeQueue"
  , "OpTypeReserveId"
  , "OpTypeRuntimeArray"
  , "OpTypeSampler"
  , "OpTypeStruct"
  , "OpTypeVector"
  , "OpTypeVoid"
  , "OpUConvert"
  , "OpUDiv"
  , "OpUGreaterThan"
  , "OpUGreaterThanEqual"
  , "OpULessThan"
  , "OpULessThanEqual"
  , "OpUMod"
  , "OpUndef"
  , "OpUnordered"
  , "OpUnreachable"
  , "OpVariable"
  , "OpVariableArray"
  , "OpVectorExtractDynamic"
  , "OpVectorInsertDynamic"
  , "OpVectorShuffle"
  , "OpVectorTimesMatrix"
  , "OpVectorTimesScalar"
  , "OpWaitGroupEvents"
  , "OpWritePipe"
  ]

declareAllOps :: Q [Dec]
declareAllOps = mapM declareOp ops

genAllOpInstances :: Q [Dec]
genAllOpInstances = liftM concat $ mapM genOpInstance ops
